# -*- coding: utf-8 -*-
"""Scrapping_tools.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHPSoLq1u_1eD2dmO5eIpH1SnC2zdADm
"""

!pip install requests
!pip install beautifulsoup4

"""Source https://codeburst.io/web-scraping-101-with-python-beautiful-soup-bb617be1f486"""

import re
from bs4 import BeautifulSoup
import requests
import pickle
import os

"""Get the text from each individual page link"""

def get_text_from_link(page_link):
  page_response = requests.get(page_link, timeout=5)
  page_content = BeautifulSoup(page_response.content, "html.parser")
  textContent = []
  has_enough_paragraph = True
  i = 0
  while has_enough_paragraph:
      try:
        page_content.find_all("p")[i]
      except:
        has_enough_paragraph = False
      if(has_enough_paragraph):
        paragraphs = page_content.find_all("p")[i].text
        i += 1
        if(":" in paragraphs):
          textContent.append(paragraphs)
          # print(paragraphs)
  return textContent
def get_href_from_link(page_link):
  page_response = requests.get(page_link, timeout=5)
  page_content = BeautifulSoup(page_response.content, "html.parser")
  links = []
  for link in page_content.find_all('a'):
    if ("series-" in link.get('href')):
      links.append(link.get('href'))
  return links

def create_map_from_series_to_content(head_link):
  links = get_href_from_link(head_link)
  d = dict()
  for link in links:
    herf_abbreviation = re.findall("series-\d+-episode-\d+", link)[0]
    d[herf_abbreviation] = get_text_from_link(link)
  return d

"""Scrapping the data online (comments out if has the data.pkl exist)"""

# head_link = 'https://bigbangtrans.wordpress.com/'
# dic = create_map_from_series_to_content(head_link)
# filename = 'data.pkl'
# if not os.path.isfile(filename):
#    with open(filename,'wb') as file:
#        pickle.dump(dic, file)
#    file.close()

"""Load the data from data.pkl"""

data_file = open('data.pkl', 'rb')
data_dict = pickle.load(data_file)
data_file.close()
# print(data_dict.keys())
# print(data_dict["series-7-episode-15"])

